### PR TITLE
Added Feature to display Node Allocation through Gauge Chart

### PR DESCRIPTION
**Pull request by Imads608**
Screenshot of the Feature below
Component can also display Gauge Charts for Memory and CPU if props are provided.

@javier-op / @dgkanatsios  let me know if anything else needs to be done here :)

image

### CODE REVIEW

**Comment by javier-op** [comment]
Hey, the gauge looks great!
Some small comments, you can see them in the gif below:

1. When you have multiple nodes, there is a shadow under the rows that leaves a blank
2. When you hover over the row, the text moves due to the new "View metric" tag
3. The tag itself is not clickable

node_gauge

**Comment by Imads608** [comment]
Thanks Javier! I'll take a look and try to make those changes.

**Comment by Imads608** [comment]
@javier-op , I've made the changes as you suggested. 
I'm not sure if I understood your first point on the shadows under the rows when we have multiple nodes.
But I think the other two should be fixed. 

Let me know your thoughts!

**Review by javier-op — APPROVED** [review]
Amazing :shipit:

**Comment by Imads608** [comment]
> Amazing :shipit:

Thanks! Could you merge? 
Seems I don't have permissions haha

**Comment by Imads608** [comment]
Actually, sorry I think forgot to change the Gauge's configuration to be orange/red from 75-100% instead of 0-25%
That would make more sense to show that for Allocation.

What do you guys think @javier-op / @dgkanatsios

**Comment by dgkanatsios** [comment]
yeah, let's do it! also, any chance we can show all gauges for all Nodes at the same time? (definitely for a separate PR :D)

**Comment by javier-op** [comment]
Ah the colors of the gauge, yeah that would make more sense. Could you make a separate pr?

**Comment by Imads608** [comment]
@javier-op yeah will do!
@dgkanatsios sounds like a great idea :D, maybe I can start to be an open-source contributor for the project instead of just the hackathon :)

**Pull request merged**
